### ISSUE TITLE
The targets overlap on pump mode

### ISSUE THREAD

**Issue by s34nvideos** [dguzek/Simply-Love-SM5#146]
The targets overlap on pump mode.

1. Select pump as the game
2. Pick a chart and play
3. At the top of the screen, the arrow targets overlap each other slightly. It's really strange.

No pump game I have ever played does this, so I presume this is a bug.

**Comment by dguzek** [comment]
While this is true, I'm unable to find any other SM5 theme where the behavior is otherwise.  I'm left to assume that this overlap is intentional in the SM5 engine.

If you feel strongly that it is a bug that needs to be resolved, I would encourage you to ~~file a bug report with the StepMania project on GitHub~~ fix it in the StepMania engine yourself as that's the only way anything is going to happen regarding it.  I'm sorry that I'm unable to advise you any further than that at this time.

**Comment by s34nvideos** [comment]
There are a few themes which do not show this behavior

Step F2: https://i.ytimg.com/vi/Il5tj2WG59Q/maxresdefault.jpg
Prime 2 Theme: https://www.youtube.com/watch?v=wZvGwhidqLY&feature=youtu.be
Prime 1 Theme: Cant find link right now.

I think it would be a good addition to this theme, even as a toggle option or an ini file adjustment. It would bring me over to SL from Step F2, that's for sure!

**Comment by dguzek** [comment]
StepF2, to my understanding, is an entirely different engine project and not SM5.

The Prime 2 theme you linked to is not online due to copyright violation so I'm unable to look into it.

Generally speaking, there are many, many things broken with Simply Love in Pump game mode that I not interested in attempting to fix.  I am not looking to bring Pump players over from StepF2, just as I am not interested in having anyone use Simply Love.  I would delete the entire repository from GitHub, but that would require me to pass the project off to another existing fork, a messy, sensitive topic.

I'm sorry I can't help you on this. I am beyond burned out on this project.

**Comment by s34nvideos** [comment]
Don't do it then. Nobody is asking you to. You created this repo, you can close it or hand it off. Plenty of people willing to take it on.

There is no need to tell me to post on the stepmania github then follow me over there to tell me to do it myself. What a dick move.

If you're so angry, annoyed and pissed off, then dont do this. Simple. Dont tell everybody your life story and how much is sucks when they are trying to report an issue. I appreciate what you have done with this theme, but we clearly need somebody else at the helm here.

**Comment by ianklatzco** [comment]
Please check yourself, @s34nvideos.
