### ISSUE TITLE
Scrolling between evaluation panes doesn't work properly with Doubles on `beta` branch

### ISSUE THREAD

**Issue by Roujo** [dguzek/Simply-Love-SM5#295]
When I get to the evaluation screen, I see the judgement counts on the left and the timing graph on the right. :+1:
When I press "Right" on the left pad, I see the individual arrow judgements. :+1:
When I press "Right" again, instead of seeing the next set of panes, nothing happens visually and this Lua error appears in the logs:
```
/////////////////////////////////////////
WARNING: Error running input callback: /Themes/Simply Love/BGAnimations/ScreenEvaluation common/InputHandler.lua:155: attempt to index a nil value
WARNING: /Themes/Simply Love/BGAnimations/ScreenEvaluation common/InputHandler.lua:155: unknown(event = (null),cn = 1,ocn = 2,(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = 16,(*temporary) = 2,(*temporary) = ' is not an enum value,(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to index a nil value)
/////////////////////////////////////////
```
When I press "Right" again, the visuals don't change either, and the same error is logged.
When I press "Right" a final time, I get back to the initial screen showing judgement counts and the timing graph.

I'm on commit `bbfc3895dd71643663942cdf7dd3654a0b209c1e`, and I've confirmed that this doesn't happen on `release`. I'm pretty sure this used to work on `beta` last week or so but I'm not sure I was up to date then so maybe it broke earlier than that. =)

**Comment by teejusb** [comment]
Thanks for the bug report!

I believe I've fixed this in https://github.com/Simply-Love/Simply-Love-SM5/commit/52d41184d2b619a4956e88c44eb50163d7f9e848

It was happening because we specifically look for unnamed childs in the panes here:
https://github.com/Simply-Love/Simply-Love-SM5/blob/beta/BGAnimations/ScreenEvaluation%20common/InputHandler.lua#L155

Since I had named them, this was returning `nil` so the `GetCommand("ExpandForDouble")` call was erroring out.

**Comment by Roujo** [comment]
Oooh perfect, thank you! 😄🎉
