### ISSUE TITLE
Lua 5.3 Numbers: MusicRate formatting errors

### ISSUE THREAD

**Issue by JoseVarelaP** [dguzek/Simply-Love-SM5#349]
Given the changes to OutFox to include Lua 5.3, values represented on Lua will change, and thus can cause formatting errors when creating values.

This issue is related to the MusicRate, given its using %g as its formatting method, which I'm not even sure if its an actual key for formatting. (Lines 279 and 284 come to mind). A simple fix is to convert them into two decimal floating points. (`%.2f`)

https://github.com/Simply-Love/Simply-Love-SM5/blob/fea4906e38b8dd8ab18c933083bd48afb948b6ed/Scripts/SL-PlayerOptions.lua#L279-L287

Another issue with this, is the fact that the default value when FindInTable fails is 1, which is used **as a index value**, rather than the result, so it grabs list[1], which is the first item on the range table, which falls to 0.05x. It should be changed to 96 as a fail safe.

**Comment by teejusb** [comment]
`%g` is a valid specifier (it's loosely defined as as `the smallest representation between %f and %e`) but yeah `%.2f` definitely seems more correct here.

The second issue is also def valid. Will send out a fix.

**Comment by teejusb** [comment]
Actually wait I see why `%g` is used. It's used stringify floats and truncate trailing zeroes (so `1` music rate doesn't show up as `1.00` and `1.1` doesn't show up as `1.10`, etc.)

**Comment by natano** [comment]
> Given the changes to OutFox to include Lua 5.3, values represented on Lua will change, and thus can cause formatting errors when creating values.

@JoseVarelaP thanks for reporting the issue! I'm not familiar with the changes in lua 5.3. What do you mean with "values represented on Lua will change"? I would like to understand the issue before making a change.

**Comment by Scraticus** [comment]
> 

There are new lua types in Lua 5.2/5.3 that allow the functions we use in the engine to specify float/int/double etc. In Lua 5.0/5.1, everything is sent up as a lua_Number, which is set up as a double type, no matter what the actual object is. You could be sending up a simple 0 and it'll be converted to 0.0000000 as that's the way it used to work.

Lua 5.3 allows lua_Integer and other types which save memory and prevent a lot of needless conversions when we're sending objects up to the theme/Lua side of the game which allows for a less heavy Lua stack, and this gives a small performance boost.

We missed the %g use in Simply Love as we didn't check the rate when we did our quick test, so we were a bit surprised when everything defaulted back to 0.05 when a user was working on their ratemods.

I hope that helps with the understanding with this issue

**Comment by teejusb** [comment]
I don't quite follow the crux of the issue.

Lua 5.1 does also have lua_Integer (e.g. [here](https://github.com/stepmania/stepmania/blob/984dc8668f1fedacf553f279a828acdebffc5625/extern/lua-5.1/src/lua.h#L147)) but regardless the attached snippet of the code doesn't send anything back to the engine until we actually call `SaveSelections` and apply the music rate [here](https://github.com/Simply-Love/Simply-Love-SM5/blob/fea4906e38b8dd8ab18c933083bd48afb948b6ed/Scripts/SL-PlayerOptions.lua#L307-L311). By then it's already been converted to a number so the `%g` shouldn't be the issue there.

By the description, it sounds like the issue is that the ` SL.Global.ActiveModifiers.MusicRate` (which is always `1` at the start of a set) is being stringified to something unexpected on OutFox which makes it not findable in the `list` so it falls back to `0.05` music rate because `i` is set to `1` as the fallback. Is that correct? Could you verify what the variables/`list`s are being stringified to by adding some `Trace()`s in `LoadSelection`/`SaveSelection` and send the log?

I also did verify that `%g` in the format string does work as expected on Lua 5.3.2/5.3.4/5.3.5/5.4.3 (as shown here)
![image](https://user-images.githubusercontent.com/5017202/146143369-ec5304f9-0b1e-4ccc-a39e-37e81168015d.png)

**Comment by Jousway** [comment]
normal 5.3.5 uses doubles as values in the engine, doubles are quite heavy, when you use %g what it does is remove trailing 0's the way that floats work is that in C and C++ they are never 100% the right value, they can be 1.9999999inf instead of 2, to fix this you want to tell the string what the amount of values you want to use, try %.3g, that should fix your issue

**Comment by natano** [comment]
We performed a couple of tests with a script to find out where the differences in behavior are coming from and it turns out that Outfox yields numerically different results than plain lua 5.3.6 (and 5.3.5). Do you know why that's the case? Does Outfox's lua use a non-standard configuration?

If this was only about the rate mod it would be doable to change all the format strings, but the change seems to affect all the places where we format numbers or even just work with numbers without formatting them(?), so the impact this has is hard to predict.

the lua script: [script.lua](https://github.com/Simply-Love/Simply-Love-SM5/files/7730631/script.lua.txt)
lua 5.3.6 output: [lua5.3.6.txt](https://github.com/Simply-Love/Simply-Love-SM5/files/7730627/lua5.3.6.txt)
Outfox output: [OF.txt](https://github.com/Simply-Love/Simply-Love-SM5/files/7730628/OF.txt)
SM 5.1 output: [SM51.txt](https://github.com/Simply-Love/Simply-Love-SM5/files/7730654/SM51.txt)

**Comment by natano** [comment]
Float/double behaviour was restored in OF alpha 4.12.0, so this is not an issue anymore. Thanks for the fix!
