### ISSUE TITLE
[General] static.lua file is acting weird

### ISSUE THREAD

**Issue by minervasm** [dguzek/Simply-Love-SM5#397]
This started when I was trying to figure out a stepmania build to put in our cabinet.
SM5.1-b2 was the smoothest one ingame, putting us at 200 fps ingame but at a solid 15~30fps during the menus due to what
I thought were the BG Animations. Thing is: in outfox this wasn't happening.
I tried going to 

.Themes\Simply Love\BGAnimations\_shared background\default.lua

and I was trying to comment out the lines applying the animations, although due to the fact that I didn't have notepad++ there, I accidentally commented only line 31

`af[#af+1] = LoadActor("./Static.lua", file)`

which when I rebooted the game, fixed every sort of problem and made my cab go up from 15 fps to 130 fps.
On my normal pc I can see this line acting up as well

![immagine](https://user-images.githubusercontent.com/84421251/173638369-ff2e82ca-6c1f-41e0-ba21-2cbebbb4bc06.png)

I can see that you guys do test on powerful PCs (well, just ordinary good ones) but these things do affect low-end cabs a lot!

Hopefully it may help.

**Comment by teejusb** [comment]
Ah yeah this was brought to my attention yesterday as well. It's happening because Static.lua on this release will play videos instead of having a static png which can cause performance hits like you are seeing. I'll be more mindful of it on next release, and also remember to add a toggle about whether or not to actually playback the videos for lower end machines. Sorry about that! It *should* be safe to comment out that line by the way.

I'll leave this issue open until it's addressed.

**Comment by minervasm** [comment]
Thank you so much! Glad I could be of help :D

**Comment by teejusb** [comment]
Confined the BG videos specifically to the SRPG6 theme in v5.2.0. Should be fixed for all other visual themes.
