### ISSUE TITLE
How to show a Song's Background for the first and last 5 seconds of a song w/ RandomMovies Enabled? 

### ISSUE THREAD

**Issue by Sepluchre** [dguzek/Simply-Love-SM5#48]
Hello, I really like this theme, but I have a question:

You know how the song background shows for the last ~2 seconds of a song when Random Background Movies are enabled? Can I have it start 3 seconds earlier to last for a total of 5 seconds? In addition, can I have it show for first 5 seconds at the start of the song on the gameplay screen as well? I would like to have this globally affect ALL songs. What *.ini or *.lua file do I need to edit to make this happen, and how would I program it?

Thank you for this very nice theme, and thank you for your time.

**Comment by dguzek** [comment]
Since RandomMovies are handled by the StepMania engine (as far I know), this question might be better suited for StepMania's issue tracker.

Since it's not a bug or feature request, however, it's probably better suited to forums like Z-i-V, where you already asked this question (and I already responded) or stepmania.com.  :)

**Comment by Sepluchre** [comment]
Hello dguzek,

I am sorry for the  "double post." I had no Idea you were the user dbk2. 
With the additional information you provided, I will follow your 
suggestion and contact the Stepmania developers (or at least try).

Thank you once again.

**Comment by dguzek** [comment]
No problem!  StepMania has an IRC channel where you can probably find a quick answer to this question.

#stepmania-dev on irc.freenode.net
