### ISSUE TITLE
No Noteskins Found For Mac Issue

### ISSUE THREAD

**Issue by kirbypoyo345** [dguzek/Simply-Love-SM5#63]
So I downloaded this game called stepmania but when I try to run it, it will pop up a message saying "No Noteskins Found" Please Help

**Comment by dguzek** [comment]
This is a known issue with StepMania and macOS.  You can read more about it [here](https://github.com/stepmania/stepmania/issues/1299).

I am closing this issue since it is unrelated to Simply Love.

**Comment by kirbypoyo345** [comment]
But I don't know how to do it though

**Comment by dguzek** [comment]
At this time, the fix (documented in [this comment](https://github.com/stepmania/stepmania/issues/1299#issuecomment-275114142)) requires users to be able to use the macOS terminal.  If you are unable to use the terminal to input and edit basic commands, it is not really feasible to play StepMania on macOS for the time being.  There is no fix in sight because the StepMania project does not have any macOS developers.

I understand that this is unfortunate but I am unable to help you any further with this.
