### ISSUE TITLE
No "assist" options (clap, metronome, etc.)?

### ISSUE THREAD

**Issue by ClefAria** [dguzek/Simply-Love-SM5#84]
I'm loving this theme, but one thing I enjoy are the assist options, which I can't seem to access when using this theme. Are they omitted deliberately, or is there something I can do to re-enable them?

**Comment by dguzek** [comment]
Thanks for filing this issue.

Yes, they are purposefully omitted.  The primary target audience of this theme is arcade cabinets, specifically public ones, where these options wouldn't really be appropriate.

**Comment by dguzek** [comment]
You can manually add this into your copy of Simply Love if you're interested.  You'll need to slightly modify two files.

In metrics.ini, you'll want to add this within the **&#91;ScreenPlayerOptions&#93;** section around [line 668](https://github.com/dguzek/Simply-Love-SM5/blob/master/metrics.ini#L668), if your theme is up-to-date:

```ini
LineAssist="list,Assist"
```

Additionally, in *./Scripts/SL-Helpers.lua*, you'll need to change [line 163](https://github.com/dguzek/Simply-Love-SM5/blob/master/Scripts/SL-Helpers.lua#L163) so that it includes the text `Assist,` in the list of available modifiers.  Like this:

```lua
return "SpeedModType,SpeedMod,Mini,Perspective,NoteSkin2,Judgment,BackgroundFilter,MusicRate,Difficulty,Assist,ScreenAfterPlayerOptions"
```

Hopefully this helps.
