### ISSUE TITLE
song statistics during gameplay causes FPS to drop progressively throughout the song

### ISSUE THREAD

**Issue by werdwerdus** [dguzek/Simply-Love-SM5#89]
When the "step statistics" are enabled during gameplay, the FPS will drop more and more as the song is played. The FPS is constant when step statistics are disabled. The CPU/memory usage doesn't seem to be significantly different with statistics enabled. 

For example, I started the the 10-minuted Hallucinogen chart from French Coast Stamina 2, the song started about 100fps, the FPS steadily/linearly declined, and after about 4 minutes the game had declined to below 40fps. With statistics disabled the FPS stays constant around 100fps through the entire song.

I am on Arch Linux using SM 5.1-new Beta 1 and Simply Love 4.5, the same problem was happening with 5.0.12 as well. It is an Intel NUC dual-core with 4gb ram.

**Comment by dguzek** [comment]
This is a valid complaint.  Unfortunately, there's nothing I can think of changing theme-side to improve its performance at this time.  It sounds like your PC is progressively struggling to render the accumulating ActorMultiVertex data that draws the line that tracks your health meter across the duration of the song.

Do you have a dedicated video card or are you using on-board/integrated graphics?  I think this would have more of an impact than your processor or RAM here (but, I don't really know enough about how all this actually works, to be honest).

If you have `SmoothLines` enabled, you could try turning them off in your Preferences.ini file by setting `SmoothLines=0`.

**Comment by werdwerdus** [comment]
I am using the NUC integrated graphics. SmoothLines is off. SoundDevice was not specified but I added hw:0 and there is no difference in framerates.

Thanks for the info. I guess I'll have to disable statistics for long songs.

**Comment by dguzek** [comment]
I'm incredibly impressed that SM5 runs smoothly on integrated graphics for you at all (when Step Statistics are disabled).  My experiences have quite the opposite.  

I (can't say with any certainty, but I) strongly suspect the problem would be resolved if you were able to use a dedicated video card.  For example, the ITG dedicab I previously maintained had a GeForce GTX 960 in order to maintain a steady framerate at 1920x1080@144hz.  That's an example of the upper extreme. Others have found success using a GeForce GT 520 to run 640x480@60hz.

Sorry I can't help any more.

**Comment by dguzek** [comment]
> what section in the theme can I modify to turn off the health line?

You could try commenting out [these lines](https://github.com/dguzek/Simply-Love-SM5/blob/master/BGAnimations/ScreenGameplay%20underlay/PerPlayer/StepStatistics/DensityGraphs/default.lua#L148-L173) which define the "lifeline" as well as [line 179](https://github.com/dguzek/Simply-Love-SM5/blob/master/BGAnimations/ScreenGameplay%20underlay/PerPlayer/StepStatistics/DensityGraphs/default.lua#L179) which then adds that definition to the overall ActorFrame.

**Comment by dguzek** [comment]
I could probably change the code to check if the lifeline actually has changed its y-value since the last sample.  If it hasn't changed, just extend the previous vertex in the line to be longer.  Only add new vertex data when it is necessary.

Such a change would not fix every possible scenario, but might help some.  I might get around to it eventually, but my work on this project is currently on indefinite hiatus.

**Comment by dguzek** [comment]
I've gone ahead and implemented what I described in my previous comment in commit 939fd371fe981b7a41c147c1e288300e26f74f71.  This should offer a modest performance improvement in the general case where the lifeline is sometimes moving around but also sometimes stable.  

In the case where the lifeline is 100% stable, the lifeline would conclude a song consisting of only 2 vertices (a starting point and an endpoint).  In the case where the lifeline is constantly jumping around, this commit would not change the final vertex count whatsoever, and performance could still be an issue.

As I note in the commit message, *truly nothing beats having a dedicated video card*.  I'm going to close this issue now as I do not believe there is anything else I can do at this time to improve the performance for you.

**Comment by dguzek** [comment]
Major thanks to @andrewipark for pull request #93 which addresses this issue further and more aggressively.
