### ISSUE TITLE
FPS Capped at 30FPS During Rainbow Mod

### ISSUE THREAD

**Issue by dougshell** [dguzek/Simply-Love-SM5#98]
Is this behavior intended?

I have 120fps without rainbow, but 30fps during screens in which rainbow mode can be perceived. FPS jumps to 120 in screens where the effects of rainbow mode are hidden. ie during gameplay.

**Comment by dguzek** [comment]
It's not intentional, but it sounds about right.  RainbowMode draws 4x as many hires Actors on screen simultaneously as non-RainbowMode does.

**Comment by dougshell** [comment]
Intended as definitely not the correct term.  I am currently using a dedicated GPU but it is quite old. I plan to upgrade anyways, but until then, do you know of rainbow mode running 60+ on midrange hardware (for instance nvidia760+/ amd rx 460+

You may not be familiar with the hardware, but I am hoping someone else will chime in.

**Comment by StefanoFiumara** [comment]
I am running an Intel i3-4360 Haswell processor on my cabinet with no dedicated graphics card, I do not experience any frame drops while using rainbow mode, the cabinet holds a steady 60hz throughout.

**Comment by dguzek** [comment]
What resolution do you play at @StefanoFiumara?

**Comment by StefanoFiumara** [comment]
sorry, edited my previous comment, 1280x768.

**Comment by dougshell** [comment]
I am running at 1920x1080 with an it 6600k @4.8ghz, I am also running an rx270 gpu with 2gb of vram

**Comment by StefanoFiumara** [comment]
I should mention that I am running Ubuntu 14.04 64bit and either 8 or 4gb
of ram (I don't quite remember).

I am not sure if performance is better or worse on windows.

**Comment by dguzek** [comment]
@dougshell – what do you have your `VideoRenderers` preference set to?

Since you are using Windows, yours will presumably be set to `VideoRenderers=opengl,d3d`.   You could try reversing the order so that it is `VideoRenderers=d3d,opengl` to use d3d as your video renderer instead of opengl.  From what I understand, d3d sometimes performs better on Windows when the hardware is older.

Do note, however, that SM5's implementation of its own d3d code is incomplete, and that certain, non-essential features in the theme and certain effects in some scripted simfiles no longer work.  

Most notably, render-to-texture doesn't exist in SM5's d3d implementation, meaning that Simply Love's screenshot animation will be broken.  Screenshots will still be saved to disk correctly, but the theme's associated animation that uses an `ActorFrameTexture` won't render properly.  Additionally, any scripted simfiles that use `ActorFrameTexture` actors will break.

**Comment by dougshell** [comment]
VideoRenderers was set to =opengl,3d3. Changing them to 3d3,opengl gained a 50% performance increase (from 30fps to around 40-45)  Dropping from 1080x1920 to 900x1600 brought it to a stable 60fps in the main menu and a 120 stable in game.

I am happy with these results, and I should not have down played the usefulness of reducing resolution as the style of visual assets used in Simply Love are EXTREMELY forgiving of resolution drops.

Thank you once again for your assistance.  Unless you would like further testing, I would consider this issue CLOSED
